// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function BringToFrontOrLaunch(arg1:string,arg2:string):Promise<void>;

export function GetDesktopFiles():Promise<Array<main.DesktopFileForFE>>;

export function WindowHide():Promise<void>;
