// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDesktopFilesForFE() {
  return window['go']['main']['App']['GetDesktopFilesForFE']();
}

export function OnIconClick(arg1, arg2) {
  return window['go']['main']['App']['OnIconClick'](arg1, arg2);
}

export function WindowHide() {
  return window['go']['main']['App']['WindowHide']();
}
