// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BringToFrontOrLaunch(arg1, arg2) {
  return window['go']['main']['App']['BringToFrontOrLaunch'](arg1, arg2);
}

export function GetDesktopFiles() {
  return window['go']['main']['App']['GetDesktopFiles']();
}

export function StartTicker() {
  return window['go']['main']['App']['StartTicker']();
}

export function TrackMouse() {
  return window['go']['main']['App']['TrackMouse']();
}

export function WindowHide() {
  return window['go']['main']['App']['WindowHide']();
}
